OPTIONS (skip=1, SILENT=all)
LOAD DATA
INFILE 'KYNovBiomet.txt'
BADFILE 'bio_bad.txt'
DISCARDFILE 'bio_dsc.txt'
replace into TABLE bio_2011_raw
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
EMPLOYEE_ID,
LASTNAME,
FIRSTNAME,
gender,
DOB date "mm/dd/rr",
GLUCOSE,
CHOLESTEROL,
TRIGLYCERIDES,
HDL,
LDL,
HEIGHT,
WEIGHT,
SBP,
DBP)